version: '3'
services:
  product-service:
    build:
      context: .
      dockerfile: deploy/product-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=localhost
      - CORS_ORIGIN=http://localhost:*
      - COMMON_RATE_LIMIT_WINDOW_MS=1000
      - COMMON_RATE_LIMIT_MAX_REQUESTS=20